import {
    mdiAccountCogOutline, mdiShopping, mdiBankCircleOutline,
    mdiCardAccountPhone, mdiCashMultiple,
    mdiPackageVariant, mdiPackageVariantClosed, mdiFormatListBulletedType, mdiTrademark,
    mdiCartArrowDown, mdiCashRegister, mdiAccount, mdiTruck, mdiTruckDelivery, mdiCreditCardOutline,
    mdiFileDocumentOutline, mdiClipboardList, mdiPercent, mdiCurrencyUsd,
    mdiOfficeBuilding, mdiAccountHardHat
} from "@mdi/js";
import { NodeMenu } from "@/types/NodeMenu";

export const menuBusinessItems: NodeMenu[] = [
    {
        id: 0,
        label: "Admin",
        icon: mdiAccountCogOutline,
        iconSize: 1,
        target: "",
        level: 0,
        nodes: [
            {
                id: 1,
                label: "Business",
                icon: mdiOfficeBuilding,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
            {
                id: 2,
                label: "My Assignments",
                icon: mdiAccountHardHat,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
        ],
    },
    {
        id: 1000,
        label: "Product Management",
        icon: mdiShopping,
        iconSize: 1,
        target: "",
        level: 0,
        nodes: [
            {
                id: 1001,
                label: "Brands",
                icon: mdiTrademark,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
            {
                id: 1002,
                label: "Categories",
                icon: mdiFormatListBulletedType,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
            {
                id: 1003,
                label: "Materials",
                icon: mdiPackageVariantClosed,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
            {
                id: 1004,
                label: "Products",
                icon: mdiPackageVariant,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
        ],
    },
    {
        id: 2000,
        label: "Transactions",
        icon: mdiBankCircleOutline,
        iconSize: 1,
        target: "",
        level: 0,
        nodes: [
            {
                id: 2001,
                label: "Purchases",
                icon: mdiCartArrowDown,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
            {
                id: 2002,
                label: "Sales",
                icon: mdiCashRegister,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
        ],
    },
    {
        id: 3000,
        label: "Contact Management",
        icon: mdiCardAccountPhone,
        iconSize: 1,
        target: "",
        level: 0,
        nodes: [
            {
                id: 3001,
                label: "Carriers",
                icon: mdiTruckDelivery,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
            {
                id: 3002,
                label: "Clients",
                icon: mdiAccount,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
            {
                id: 3003,
                label: "Suppliers",
                icon: mdiTruck,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },

        ],
    },
    {
        id: 4000,
        label: "Financial Management",
        icon: mdiCashMultiple,
        iconSize: 1,
        target: "",
        level: 0,
        nodes: [
            {
                id: 4001,
                label: "Currencies",
                icon: mdiCurrencyUsd,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
            {
                id: 4002,
                label: "Invoices",
                icon: mdiFileDocumentOutline,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
            {
                id: 4003,
                label: "Payments Method",
                icon: mdiCreditCardOutline,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },

            {
                id: 4004,
                label: "Remittances",
                icon: mdiClipboardList,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
            {
                id: 4005,
                label: "Taxes",
                icon: mdiPercent,
                iconSize: 1,
                target: "",
                level: 1,
                nodes: [],
            },
        ],
    },
];